name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # On Node 14, we got the following error on CI
        # npm ERR! @typescript-eslint/utils not accessible from @oursky/eslint-plugin
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: make check-rules-are-up-to-date
    - run: make check-all-rules-are-considered
    - run: npm run typecheck
    - run: npm run format
    - run: npm run test
